extends:
 - ./lint/eslintrc-gjs.yml

rules:
  consistent-return: error
  key-spacing:
    - error
    - mode: minimum
      beforeColon: false
      afterColon: true
  object-curly-spacing:
    - error
    - always
  prefer-arrow-callback: error
globals:
  global: readonly
overrides:
  excludedFiles:
    - rxjs.js
