---
- hosts: all
  gather_facts: yes
  tasks:
    - name: Upgrade packages
      ansible.builtin.dnf:
        name: "*"
        state: latest
      become: yes

    - name: Install packages
      ansible.builtin.dnf:
        name:
          - gnome-session-xsession
          - gnome-extensions-app
          - vte291
          - libxslt
          - gtk3-devel
          - gtk4-devel
          - glib2-devel
          - xdotool
          - xautomation
          - sudo
          - make
          - patch
          - jq
          - unzip
          - git
          - npm
          - gdm
          - xorg-x11-server-Xvfb
        state: latest
      become: yes

    - name: Check if reboot is necessary
      ansible.builtin.command: dnf needs-restarting -r
      register: needs_reboot
      failed_when: needs_reboot.rc > 1
      changed_when: needs_reboot.rc == 1
      become: yes

    - name: Reboot
      ansible.builtin.reboot:
      when: needs_reboot.changed
      become: yes

    - name: Check if systemd services should be restarted
      ansible.builtin.command: dnf needs-restarting -s
      register: needs_service_restart
      changed_when: needs_service_restart.stdout_lines | length > 0
      when: ansible_facts['distribution_version'] is version('33', '>=')
      become: yes

    - name: Restart updated systemd services
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: restarted
      loop: "{{ needs_service_restart.stdout_lines }}"
      when: needs_service_restart.changed
      become: yes

    - name: Set graphical.target as the default
      ansible.builtin.file:
        path: /etc/systemd/system/default.target
        src: /usr/lib/systemd/system/graphical.target
        state: link
      become: yes

    - name: Start graphical.target
      ansible.builtin.systemd:
        name: graphical.target
        state: started
      become: yes

    - name: npm ci
      ansible.builtin.command: npm ci
      args:
        chdir: /vagrant/

    - name: make install
      ansible.builtin.command: xvfb-run make install
      args:
        chdir: /vagrant/

    - name: Detect running GNOME X11 session
      ansible.builtin.command: systemctl --user is-active gnome-session-x11.target
      register: gnome_x11_session
      ignore_errors: yes

    - name: Detect running GNOME Wayland session
      ansible.builtin.command: systemctl --user is-active gnome-session-wayland.target
      register: gnome_wayland_session
      ignore_errors: yes

    - name: Enable the extension
      ansible.builtin.command: gsettings set org.gnome.shell enabled-extensions "['ddterm@amezin.github.com']"

    - name: Restart GNOME X11 session
      ansible.builtin.command: busctl --user call org.gnome.Shell /org/gnome/Shell org.gnome.Shell Eval s 'Meta.restart("Restarting...")'
      when: gnome_x11_session is succeeded

    - name: Stop GNOME Wayland session - must be restarted to load updated extension
      ansible.builtin.command: killall gnome-shell
      when: gnome_wayland_session is succeeded
