---
- hosts: all
  tasks:
    - name: npm ci
      ansible.builtin.command: npm ci
      args:
        chdir: /vagrant/

    - name: Check if gtk4-builder-tool is available
      ansible.builtin.stat:
        path: /usr/bin/gtk4-builder-tool
      register: gtk4_builder_tool

    - name: make install
      ansible.builtin.command: xvfb-run make WITH_GTK4={{ 'yes' if gtk4_builder_tool.stat.exists else 'no' }} install
      args:
        chdir: /vagrant/

    - name: Enable the extension
      ansible.builtin.command: gsettings set org.gnome.shell enabled-extensions "['ddterm@amezin.github.com']"

    - name: List existing sessions
      ansible.builtin.command: loginctl list-sessions -o json
      register: sessions

    - name: Terminate existing sessions
      ansible.builtin.command: loginctl terminate-session {{ item.session }}
      become: yes
      loop: "{{ sessions.stdout | from_json | selectattr('seat') | selectattr('uid', '==', ansible_facts['real_user_id']) }}"

    - name: Ensure graphical.target is started
      ansible.builtin.systemd:
        name: graphical.target
        state: started
      become: yes
