---
- hosts: all
  tasks:
    - name: npm ci
      ansible.builtin.command: npm ci
      args:
        chdir: /vagrant/

    - name: make install
      ansible.builtin.command: xvfb-run make install
      args:
        chdir: /vagrant/

    - name: Detect running GNOME X11 session
      ansible.builtin.command: systemctl --user is-active gnome-session-x11.target
      register: gnome_x11_session
      ignore_errors: yes

    - name: Detect running GNOME Wayland session
      ansible.builtin.command: systemctl --user is-active gnome-session-wayland.target
      register: gnome_wayland_session
      ignore_errors: yes

    - name: Enable the extension
      ansible.builtin.command: gsettings set org.gnome.shell enabled-extensions "['ddterm@amezin.github.com']"

    - name: Restart GNOME X11 session
      ansible.builtin.command: busctl --user call org.gnome.Shell /org/gnome/Shell org.gnome.Shell Eval s 'Meta.restart("Restarting...")'
      when: gnome_x11_session is succeeded

    - name: Stop GNOME Wayland session - must be restarted to load updated extension
      ansible.builtin.command: killall gnome-shell
      when: gnome_wayland_session is succeeded

    - name: Ensure graphical.target is started
      ansible.builtin.systemd:
        name: graphical.target
        state: started
      become: yes
