name: lint

on: [push, pull_request]

jobs:
  eslint:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '12'
    - run: npm install eslint
    - run: npx eslint .

  glib-compile-schemas:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - run: ./do-in-docker.sh make schemas/gschemas.compiled

  gtk-builder-validate:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - run: ./do-in-docker.sh make gtk-builder-validate
