name: pack

on: push

jobs:
  pack:
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/amezin/gnome-shell-pod-34:master

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
    - run: npm ci
    - run: xvfb-run make pack
    - uses: actions/upload-artifact@v2
      with:
        name: shell-extension
        path: "*.shell-extension.zip"

  release:
    needs: pack
    if: startsWith(github.ref, 'refs/tags/v')
    permissions:
      contents: write

    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/amezin/gnome-shell-pod-34:master

    steps:
    - uses: actions/download-artifact@v2
      with:
        name: shell-extension
    - uses: softprops/action-gh-release@1e07f4398721186383de40550babbdf2b84acfc5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: "*.shell-extension.zip"
        draft: true
        generate_release_notes: true
