name: pack

on: [push, pull_request]

jobs:
  pack:
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/amezin/gnome-shell-extension-ddterm-ci-docker-image:master

    steps:
    - uses: actions/checkout@v2
    - run: xvfb-run make pack
    - uses: actions/upload-artifact@v2
      with:
        name: shell-extension
        path: "*.shell-extension.zip"
    - uses: amezin/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/v')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: "*.shell-extension.zip"
        draft: true
  test:
    runs-on: ubuntu-20.04
    needs:
      - pack
    strategy:
      fail-fast: false
      matrix:
        fedora-version:
          - '32'
          - '33'
          - '34'
        backend:
          - 'xsession'
          - 'wayland-nested'
          - 'wayland-nested-highdpi'
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
      with:
        name: shell-extension
    - run: sudo podman pull ghcr.io/amezin/gnome-shell-pod-${{ matrix.fedora-version }}-${{ matrix.backend }}:master
    - run: sudo ./run_test_podman.sh ghcr.io/amezin/gnome-shell-pod-${{ matrix.fedora-version }}-${{ matrix.backend }}:master
    - uses: actions/upload-artifact@v2
      with:
        name: screenshot-${{ matrix.fedora-version }}-${{ matrix.backend }}
        path: "Xvfb_screen*.png"
      if: always()
