name: test

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        image:
          - 'gnome-shell-pod-32'
          - 'gnome-shell-pod-33'
          - 'gnome-shell-pod-34'
          - 'gnome-shell-pod-35'
        session:
          - 'TestXSession'
          - 'TestWayland'
          - 'TestWaylandHighDpi'
          - 'TestWaylandDualMonitor'
        exclude:
          - image: 'gnome-shell-pod-33'
            session: 'TestWaylandDualMonitor'
    env:
      IMAGE: ghcr.io/amezin/${{ matrix.image }}:master
      PY_COLORS: 1
      TOX_TESTENV_PASSENV: PY_COLORS GITHUB_ACTIONS
      TOXENV: py3-ghactions
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v3
    - run: sudo apt-get install -y python3-gi libmagickwand-6.q16-6 tox
    - run: npm ci
    - run: sudo podman pull "${{ env.IMAGE }}"
    - run: sudo podman run --rm -i -v "${PWD}:${PWD}" -w "${PWD}" "${{ env.IMAGE }}" xvfb-run make test-deps
    - run: tox -vv --notest --sitepackages
      working-directory: test
    - run: tox --sitepackages -- --podman sudo podman --container-image "${{ env.IMAGE }}" -n 2 --screenshot-failing-only -v "test_extension.py::${{ matrix.session }}"
      working-directory: test
    - uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.session }}-${{ matrix.image }}
        path: |
          test/report.html
          test/junit.xml
          test/assets
      if: always()
