name: test

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/amezin/gnome-shell-extension-ddterm-ci-docker-image:master
      options: --privileged --cgroupns=private --tmpfs /tmp --tmpfs /run

    strategy:
      fail-fast: false
      matrix:
        image:
          - 'gnome-shell-pod-fedora-35'
          - 'gnome-shell-pod-fedora-36'
          - 'gnome-shell-pod-debian-11'
          - 'gnome-shell-pod-ubuntu-20.04'
          - 'gnome-shell-pod-ubuntu-21.10'
        session:
          - 'TestXSession'
          - 'TestWayland'
          - 'TestWaylandHighDpi'
          - 'TestWaylandDualMonitor'

    env:
      IMAGE: ghcr.io/amezin/${{ matrix.image }}:master
      PY_COLORS: 1
      TOX_TESTENV_PASSENV: PY_COLORS GITHUB_ACTIONS
      TOXENV: py3-ghactions

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
    - run: npm ci
    - run: xvfb-run make test-deps
    - run: tox -vv --notest --sitepackages
      working-directory: test
    - run: podman pull "${{ env.IMAGE }}"
    - run: tox --sitepackages -- --container-image "${{ env.IMAGE }}" -n 2 --screenshot-failing-only -v "test_extension.py::${{ matrix.session }}"
      working-directory: test
    - uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.session }}-${{ matrix.image }}
        path: |
          test/report.html
          test/junit.xml
          test/assets
      if: always()
